theme = "monokai"

[editor]
auto-pairs = false
scrolloff = 8
middle-click-paste = false
gutters = ["line-numbers", "diagnostics"]

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "file-type"]
center = []
right = ["diagnostics", "register", "position", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
C-q = ":q!"
C-s = ":w"
C-e = "command_mode"

[keys.normal]
C-s = ":w"
C-q = ":q!"
C-w = ["move_prev_word_start", "delete_selection"]
C-a = ["move_prev_word_start", "collapse_selection"]
C-d = ["move_next_word_end", "collapse_selection"]
C-v = "paste_before"
C-c = "yank"
tab = "indent"
S-tab = "unindent"
C-left = ["move_prev_word_start", "collapse_selection"]
C-right = ["move_next_word_end", "collapse_selection"]
C-p = "command_palette"
C-e = "command_mode"
C-f = "search"
c = "toggle_comments"
l = "extend_line_below"
L = "extend_to_line_bounds"
x = { w = "increment", s = "decrement", u = "switch_to_uppercase", l = "switch_to_lowercase", k = "switch_case", f = "select_regex", d = "split_selection", j = "join_selections", x = "toggle_comments" }
s = { r = "select_regex", s = "split_selection", n = "split_selection_on_newline", m = "merge_selections", t = "trim_selections", c = "collapse_selection" }
