theme = "my_theme"

[editor]
auto-pairs = false
scrolloff = 8
middle-click-paste = false
gutters = ["diagnostics", "line-numbers"]

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"
C-q = ":q!"
C-w = ["move_prev_word_start", "delete_selection"]
C-a = ["move_prev_word_start", "collapse_selection"]
C-d = ["move_next_word_end", "collapse_selection"]
C-v = "paste_before"
C-c = "yank"
tab = "indent"
S-tab = "unindent"
C-left = ["move_prev_word_start", "collapse_selection"]
C-right = ["move_next_word_end", "collapse_selection"]
C-p = "command_palette"
C-e = "command_mode"
C-f = "search"
X = "toggle_comments"
x = { w = "increment", s = "decrement", u = "switch_to_uppercase", l = "switch_to_lowercase", k = "switch_case", f = "select_regex", d = "split_selection", j = "join_selections", x = "toggle_comments" }
