blocks:
    - permission
    - name
    - size
    - date

date: relative

hyperlink: auto

size: short

sorting:
    column: name
    dir-grouping: first

symlink-arrow: "->"

ignore-globs:
    - .git
