AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/For:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
